### ISSUE TITLE
Username of local Protect user: Aborted!

### ISSUE THREAD

**Issue by skotman01** [unifi-toolbox/unifi-protect-video-downloader#38]
Using CloudKey Gen2 +, running docker image on ubuntu linux. When running no matter what user I enter it get the following error:

Username of local Protect user: Aborted!

**Comment by lubikx** [comment]
@skotman01 i recently upgraded cloudkey gen2 firmware and it installs unifi os or something like that, the api is now in different location and authentication is not token based but cookie based (you can check if your protect controller is running on port 7443 or just /protect in web browser)

Try to follow the instructions as with UDM: https://github.com/unifi-toolbox/unifi-protect-video-downloader#for-udm-based-protect-installations

**Comment by danielfernau** [comment]
Good suggestion, @lubikx ! If the new OS on the CloudKey behaves the same compared to UDM Pro, that should work.
@skotman01 : let me know if that solves the auth problem for you -- in case it does, I'll update the docs and the README accordingly.

**Comment by lubikx** [comment]
@danielfernau I tried to make it work, authentication and camera list was working but then the proxy docker container was throwing errors when trying to actually download the videos. @skotman01 let us know if it works for you. I was actually using v1 main.py script still so I made it work by small changes in the v1 script, it is actually very simple (just use port 443, for authentication use /api/auth/login and save the cookie, do not call get_api_access_key, use cookie instead of token and use URL /proxy/protect/api/video/export for download_file). I'm attaching original and modified file, unfortunately cannot send you a PR because it is based on old version but it might help you in modifing v2 to support both firmwares and dream machine without using the proxy (eg. with some command line option --firmware 1/2 or autodetect based on api url).
[main-ck-v1-v2.zip](https://github.com/unifi-toolbox/unifi-protect-video-downloader/files/5867253/main-ck-v1-v2.zip)

**Comment by danielfernau** [comment]
Hi @skotman01 and @lubikx 

Thanks for your help and patience. I've now updated the tool to be compatible with the new UniFi OS firmware. Also, the `unifi-udm-api-proxy`is no longer required. It now runs out-of-the-box using [just one Docker command](https://github.com/unifi-toolbox/unifi-protect-video-downloader/tree/c06000e9e2d423651ce73c0669dca06056a6ba14#for-protect-servers-with-unifi-os). 

The new release – [v2.0.1](https://github.com/unifi-toolbox/unifi-protect-video-downloader/releases/tag/v2.0.1) – is now available for download. Please have a look and let me know in case you encounter any additional issues.
